set-option -g default-shell /opt/homebrew/bin/fish

# Terminal Colors
set -as terminal-features ",xterm-ghostty:RGB"
set -as terminal-overrides ",xterm-ghostty:Tc"

set -g default-command fish

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @floax-bind '-n M-p'

# Enable key passthrough
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

bind-key "e" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh

# Theme
# source-file ~/.config/tmux/themes/everforest.conf
source-file ~/.config/tmux/themes/vauge.conf

# Configure Tmux
set -g status-position top
set -g status-style "bg=default"
set -g status-justify absolute-centre
set -g status-bg default

# pane border look and feel
setw -g pane-border-status off
setw -g pane-border-style fg=#cdcdcd
setw -g pane-active-border-style fg=#6e94b2

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_alt},fg=default,bold]  #S },#{#[bg=default,fg=#{@thm_blue}]  #S }}"
set -ga status-left "#[bg=default,fg=#{@thm_alt},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_purple}]  #{pane_current_command} "
set -ga status-left "#[bg=default,fg=#{@thm_alt},none]│"
set -ga status-left "#[bg=default,fg=#{@thm_pink}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=default,fg=#{@thm_purple}]#(whoami) "

# window look and feel
set -g automatic-rename-format ""
set -g renumber-windows on

set -g window-status-format " #{?#{!=:#{window_name},},#I: #W,#I} "
set -g window-status-style "bg=default,fg=#{@thm_white}"
set -g window-status-last-style "bg=default,fg=#{@thm_red}"
set -g window-status-activity-style "bg=#{@thm_purple},fg=default"
set -g window-status-bell-style "bg=#{@thm_purple},fg=default,bold"
set -gF window-status-separator "#[bg=default,fg=#{@thm_alt}]│"

set -g window-status-current-format " #{?#{!=:#{window_name},},#W,#I} "
set -g window-status-current-style "bg=#{@thm_red},fg=#{@thm_black},bold"


# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-floax'

bind r source-file ~/.config/tmux/tmux.conf

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run 'tpack init'
