# Colors
set -g @theme-foreground "#D3C6AA"
set -g @theme-background "#2D353B"
set -g @theme-red        "#E67E80"
set -g @theme-yellow     "#DBBC7F"
set -g @theme-green      "#A7C080"
set -g @theme-blue       "#7FBBB3"
set -g @theme-purple     "#7FBBB3"
set -g @theme-orange     "#E69875"
